language: node_js
node_js:
- '6.9.1'
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  on:
    branch: release
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_API_KEY"