language: node_js
node_js:
- 6.9.1
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: alexistessierdev@gmail.com
  api_key:
    secure: BG7QcZeLkSzvc9rdV9jxRNvN+xNSCGQh4/VxGwGY7nEgw9jIZQBz7qAicZ/6fPV+7NLcUAPvRRp9wrSSGcMdivMChmBfG4m0rNNWwTnStdZ4HJN0k92tYuZCKp4dz2rELT7utOrE4lAPmlTq+nSrmQ8CzscwFjhCU/si5+Ruy8gr2FjsEMxSM/+Iq0NclDClbho992D6/4SHkkkj0TfPpIPrWxmzgKRAl3BunhWGnOn5lpKu327n4+sio/t4FJ0hWoQtoxTcz6ephHBZqUw7D5LoqrSgZZkzWybhw4/c0SO7s2REj2EutonVKvpyDqm27pMJdT3V8syn36Mkp447J2K400l61mvt6jvAXEYZ9lYxgnxVxB/kWCI6R4/R2FrsW25mdzMT2+4SrGQUr6cKsSwQYA/c0cvRv8PfnwhKoBnNJM06H8qY8b7JIEBvTNtr9Wo39ogBANfFNVg2R73rB+r9fa7qnLgg25YqrH4Xe/pmaRMilqpmPuJ1rT2bbjNTVWKDndT9lxesSiTN30UEXfTTLNyhYa50Gs8w4G+sy4vMKCiNGnqzpdJcTQICNaBgGwmTsoPI5ttbIx/Gz9pbqbotOB+2iF/hlZx8F7Cfzpl0KN/JXZEeBz0cAv+7TqYO1obKQAp1uoI4Bf27WiBLXkY3yBJ2AdRFxHDS/SIDfwM=
  on:
    repo: AlexisTessier/javascript-value-locator
    branch: release