language: node_js
node_js:
- 6.9.1
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: alexistessierdev@gmail.com
  api_key:
    secure: nEHQs9cWjFsC4AYc8rQzBEGgAJpuRykICkJY3JT6anbZJN6PMd7oyl7NtGp3+2aZAkLlSS+4HVHyOgx63EAagES8GHy/OuG2i45QPUl/Y3MDYnBC0HTTbdXpEVu0sn3F6ZfS68VKfhdxiBe5QzqkW6HjNILbl/WaOoczgPYOMBUPNMf7ONjskbEzLsPVW4Eo6te0kbHuKS63X54R2z+WfqyusgIPTLiJoHU5DeQJj+qw+66LXpd6Vi4bEIiwrkWGtlsVg3oh2tkX0+F2c1JH2JIenDa9WQwAQSGXSexgyx2mH1h2gpp/L3tB5QDuNit4ls32dFWPolX2X8h4oyZzSntifjwfuxFv0WGJAGmew/im1BP8tWkjEc6szdc+UrL11WY1mKCNPRYWZinv6ed0hxP//y8X1g1PUN+WmoWdFrPBW0jjLuhswL3j6c3rSvfcEANzO4HonalZoueyzIkqXhemsV1qlvctl9wDoxcYidqLgGhrZiYn3sT3UR/iXTcAHGXQMdECtc/ASmrbQFss9d56wSe8T/7Yk9hhA38OFYX2VCFZCZPz9RqaqAyRhggzs/3zEa+2h1gNDFY1r21jI/nrBlfdEvCNZpJP/KDXXuwnn0LE3JX5g+sBeBvaAuk6Ns3Rb1XdqIRptmjh6i5FKhKnfZSgl+NUvVuIXEhET9U=
  on:
    repo: AlexisTessier/javascript-value-locator
    branch: release